# general
workers: 8

dataset: "Trento"
dataset_root: 'HSI-Lidar-Trento\\'
model_path:  "save/Trento"
seed: 42

# data options
patch_size: 9
is_labeled_pixel: False

# model options
max_iter: 5
kernel: 'rbf' # 'rbf' # if None, classic mode will be used, 'rbf', 'polynomial'
anchor_type: 'k-means' # 'random', 'k-means', 'precomputed'
smooth_coef: 1.15 #1.15  # must less than 0 or larger than 1
lambda_TV: 0.001  # $\alpha$, usually larger than 1  # or TV coefficient <= 10
weight_decay: 10000 # $\gamma$, regularization
n_anchor_in: 3  # num anchors for in-samples
n_anchor_out: 50   # num anchors for out-of-samples
# kernel approximating
n_kernel_sampling: 500





